project: 
  type: website
  
website: 
  page-navigation: true
  title: "NMFS Openscapes" 
  site-url: "https://openscapes.github.io/nmfs-openscapes" 
  repo-url: https://github.com/openscapes/nmfs-openscapes
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Openscapes, 2022"
    
  sidebar:
    logo: "images/logo-transparent-crop.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://openscapes.org
        text: "Openscapes.org"
      - icon: github
        href: https://github.com/openscapes/nmfs-openscapes
        text: "NMFS Openscapes"
      - icon: twitter
        href: https://twitter.com/openscapes
        text: "Openscapes Twitter"         

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: about-openscapes.qmd
        text: About Openscapes
      - href: about-nmfs-openscapes.qmd
        text: About NMFS Openscapes
      - section: cohorts/index.qmd
        text: Champions Cohorts
        contents: 
          - cohorts/NWFSC-spr2021.md
          - cohorts/FDD-fall2021.md
          - cohorts/NMFS-fall2021.md 
          - cohorts/AFSC-win2021.md 
          - cohorts/SEFSC-sum2022.md 
          - cohorts/NMFS-fall2022.md 
      - mentors.qmd
      - href: media.qmd
        text: Presentations and Media
      - contact.qmd


format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
