project: 
  type: website
  
website: 
  page-navigation: true
  title: "Openscapes at the CA Water Boards" 
  site-url: "https://CAWaterBoardDataCenter.github.io/swrcb-openscapes" 
  repo-url: https://github.com/CAWaterBoardDataCenter/swrcb-openscapes
  repo-actions: [edit, source, issue]
  favicon: images/openscapes_hex.png  
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By CA Water Board, 2023"
  
  sidebar:
    background: "#D9E3E4"
    logo: "images/logo-transparent.png"
    favicon: images/openscapes_hex.png
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://openscapes.org
        text: "Openscapes.org"
      - icon: github
        href: https://github.com/CAWaterBoardDataCenter/swrcb-openscapes
        text: "SWRCB Openscapes"
      - icon: twitter
        href: https://twitter.com/openscapes
        text: "Openscapes Twitter"         

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: about-openscapes.qmd
        text: About Openscapes
      - section: about_at_swrcb/index.qmd
        text: About Openscapes at the Water Boards
        contents:
          - about_at_swrcb/implementation.qmd
          - about_at_swrcb/team_guidance.qmd
      - section: cohorts/index.qmd
        text: Champions Cohorts
        contents: 
          - cohorts/swrcb_2022.qmd
          - cohorts/swrcb_2023.qmd
      - href: resources.qmd
        text: Resources
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    fontsize: 1em


filters:
  - include-files.lua
  - quarto

execute:
  freeze: auto
