---
title: "About NMFS Openscapes"
---

NMFS Openscapes is a multi-year collaboration between NOAA Fisheries science centers and [Openscapes](https://www.openscapes.org/) to provide team-based training in reproducible scientific workflows and platforms. We have had six Openscapes Champions Cohorts in 2020-2022 and have an upcoming agency-wide training with four Cohorts across multiple centers and regional offices in fall of 2022. Read [blog posts](https://www.openscapes.org/tags/noaa-fisheries/) about past NMFS Cohorts and other NMFS Openscapes activities.

## A plan to modernize NMFS teams with Open Science

### Context

Over the last decade, there have been rapid changes within the scientific community to improve the quality of science -- these advances are not related to specific methodologies, but largely around scientific culture and collaboration (collectively, 'Open Science'). Many of the techniques -- including version control, code review, reproducible reports, project management, and leadership skills -- have been widely used by industry and academic partners, but have not seen wide use in government. Open Science fosters a more efficient and equitable working environment, via improved team collaboration and knowledge sharing.

### Where we are today

Many federal agencies, including NOAA Fisheries, are experiencing a number of pressures affecting agency science. Examples include:

-   New risks affecting the kind of science we do (climate change impacts on freshwater and marine ecosystems) and requiring new analyses to deal with changing environments
-   Flat budgets amid rising operation costs and increasing costs of living (employees that leave may not be replaced)
-   A distributed workforce (employees based remotely or across multiple offices)
-   An aging workforce, associated risk of loss of data and institutional knowledge, and need for succession planning
-   Need for transparency to enhance public trust in agency science and decisions

### Our vision for the future

A number of projects across NMFS science centers have adopted Open Science practices to improve the efficiency and quality of scientific products. Examples include the development of FIMS tools for next generation stock assessment, the joint NMFS - DFO stock assessment of Pacific hake (NWFSC), ecosystem status reports for the Mid-Atlantic and New England Fishery Management Councils (NEFSC), and data products related to surveys (AFSC). Many additional projects are also deployed on the NOAA Fisheries Integrated Toolbox (FIT).

Despite these advancements, applications of Open Science best practices within NMFS are generally program-specific and maintained by one or a few team members. There is an urgent need to upskill the existing NMFS workforce with modern tooling and collaborative approaches to help our agency be nimble and tackle the challenges of the 21st century. Doing so will increase efficiency and build enduring resilience across science centers and regional offices.

Change requires both structure and flexibility, focused on inclusion and empathy, so we can elevate our peers from where they are. Similarly, collaborative team-based research requires non-technical changes to the way we work; these include documenting standard operating procedures, working inclusively within/across science centers and regional offices, and cultivating rather than reinventing products. Supporting this change in work culture demands a dynamic approach that leverages and amplifies ongoing work in global Open Science - and that is what Openscapes does, based on their team's transition to better science in less time.

### What we have done and where we are going

Since 2020, individual science centers have organized 6 cohorts with the Openscapes' Champions Program (most recently with a 2022 SEFSC Summer Cohort) demonstrating a demand at NMFS. However as not all centers (or regional offices) have access to the same levels of training funds, cohorts have not been evenly distributed across the agency. In addition, the training has thus far been limited to full-time federal staff and at many science centers, teams involve contractors and non-federal collaborators.

We are working on securing support for a 3-year national-level program modeled off of the 3-year NASA Openscapes program. Supporting Openscapes at a national level would enable sustainable adoption of Open Science workflows and more efficient NMFS teams trained in modern data science tools and team management.

### Why Openscapes?

[NOAA Fisheries](https://www.fisheries.noaa.gov/about-us) is responsible for the stewardship of the nation's ocean resources and their habitat. We provide vital services for the nation, all backed by sound science and an ecosystem-based approach to management. NOAA promotes Open Science in its work towards its mission: [NOAA Data Strategy for open and transparent data and analyses](https://sciencecouncil.noaa.gov/Portals/0/2020%20Data%20Strategy.pdf?ver=2020-09-17-150024-997).

Openscapes' long-term goal is to enable robust, inclusive, and enduring science- and data-driven solutions to global and time-sensitive challenges. They approach open science as a spectrum, as a behavior change, and as a movement. Data analysis and stewardship are entryways to meet scientists where they are, helping them develop new skill sets and mindsets while empowering them as leaders. The Openscapes Framework is team-based and particularly suited to the type of big team projects that we work on. Openscapes training is helping NMFS teams change their scientific workflows to work more openly, reproducibly, efficiently and robustly, to advance NOAA Fisheries' mission.

