---
title: "Impacts"
---

Openscapes is an ongoing internal effort at the Water Boards, with immediate and long-term impacts across the organization. Below is a space of shared successes we've heard about or seen from teams who have joined a Champions Cohort at the Water Boards! If you would like to contribute to this list, please [submit an issue](https://github.com/CAWaterBoardDataCenter/swrcb-openscapes) to this Github repository!

## Individual team successes

-   The PFAS Free Forum

-   SWAMP Manual

-   Mentor-led meetings/facilitation/skill building/leadership

-   Ongoing optional co-working among SWAMP team members as an agenda-free space to work on common tasks, knowledge sharing/skill building, and opportunity to pause and reflect on Water Boards work

## Qualitative outcomes

-   Improved individual and team interactions

-   Foster a culture of inclusion and belonging where discussion of values is safe and welcomed

    -   Direct connection to Goal 2B of the Water Boards [Racial Equity Action Plan](https://www.waterboards.ca.gov/racial_equity/docs/racial-equity-action-plan-final-en.pdf)
