---
title: "Mentors"
---

# NMFS Openscapes Mentors

The Openscapes Mentor group is a cross-NMFS mentor community. Each science center and regional office participating in the Openscapes cohorts has 1-4 mentors that help organize the local cohorts, spearhead communication with with their local leadership, act as a point-person for interested local staff, help identify local needs, and help communicate, or potentially organize, teaching resources for their local staff.

Openscapes organizes training and co-working sessions for the mentor group, so that we can all learn from each others experiences and learn new skills together.  

## Mentors

Organizers

* Leads: Julie Lowndes and Stefanie Butland (Openscapes)
* Co-Lead: Eli Holmes (NOAA Fisheries)

Center-Level Mentor group

* AFSC: Emily Markowitz, Josh London, Megsie Siple
* NEFSC: Andy Jones, Scott Large
* NWFSC: Eli Holmes, Eric Ward
* PIFSC: Amanda Bradford
* SEFSC: Adyan Rios, Molly Stevens
* SWFSC: Kevin Stierhoff



# Mentor Cohort Activities

## 2022

### July-August

The NMFS Openscapes mentor group is meeting bi-weekly. Current focus is on activities surrounding the summer cohorts at SEFSC and Cal EPA.

### Spring 

Mentors and other interested folks across science centers and regional offices met several times to plan and give presentations about NMFS Openscapes efforts to individual science centers and the NMFS Science Board.

### January-March

The AFSC Mentors met bi-weekly during the 2021-2022 AFSC cohort. 

