---
title: "Water Boards Champions Cohorts"
---

## Champions Cohorts

The Water Boards Openscapes Champions Program is a mentorship and professional development opportunity for individuals and teams at the Water Boards.

### Current and Upcoming Cohorts

[**2024 Spring Water Boards Cohort**](https://cawaterboarddatacenter.github.io/swrcb-openscapes/cohorts/swrcb_2024S.html)**:** From late-March through late-May 2024, the Water Boards will host a Champions Cohort, which will include 6 teams of no more than 6 individuals per team.

***Water Boards teams will be able to apply for this opportunity from Jan 22 - Mar 1, 2024.***

The Water Boards Openscapes Team offered to present about this work and its future in our organization to management, internal roundtables, and work groups, starting in Nov 2023 (see [presentation list](https://github.com/CAWaterBoardDataCenter/swrcb-openscapes/issues/15)). To request a presentation please email [Anna Holder](mailto:anna.holder@waterboards.ca.gov).

2024 Fall Water Boards Cohort: From mid-August through mid-October 2024, the Water Boards will host a Champions Cohort, which will include 6 teams of no more than 6 individuals per team.

***Water Boards teams will be able to apply for this opportunity from Jan 22 - Mar 1, 2024 & May 1 - Jun 30, 2024.***

### Past Cohort Summary

|                                                                  | [2023 Cohort](https://cawaterboarddatacenter.github.io/swrcb-openscapes/cohorts/swrcb_2023.html) | [2022 Cohort](https://cawaterboarddatacenter.github.io/swrcb-openscapes/cohorts/swrcb_2022.html) |
|-----------------------------------------|----------------|----------------|
| Number of Teams                                                  | 6                                                                                                | 3                                                                                                |
| Percent of RDOs Represented ( Number of RDOs )                   | 36% ( 8 )                                                                                        | 9% ( 2 )                                                                                         |
| Number of Individuals = (Teams + Instructors + Mentors)          | 31                                                                                               | 19                                                                                               |
| [**Water Boards Region, Division, or Office (RDO)**]{.underline} |                                                                                                  |                                                                                                  |
| DAS = Division of Administrative Services                        |                                                                                                  |                                                                                                  |
| DDW = Division of Drinking Water                                 | 8                                                                                                |                                                                                                  |
| DFA = Division of Financial Assistance                           |                                                                                                  |                                                                                                  |
| DIT = Division of Information Technology                         | 1                                                                                                |                                                                                                  |
| DWQ = Division of Water Quality                                  | 7                                                                                                | 7                                                                                                |
| DWR = Division of Water Rights                                   |                                                                                                  |                                                                                                  |
| OCC = Office of Chief Counsel                                    |                                                                                                  |                                                                                                  |
| OE = Office of Enforcement                                       | 1                                                                                                |                                                                                                  |
| OIMA = Office of Information Management and Analysis             | 3                                                                                                | 12                                                                                               |
| OLA = Office of Legislative Affairs                              |                                                                                                  |                                                                                                  |
| OPA = Office of Public Affairs                                   |                                                                                                  |                                                                                                  |
| OPP = Office of Public Participation                             | 1                                                                                                |                                                                                                  |
| ORPP = Office of Research, Planning, and Performance             | 6                                                                                                |                                                                                                  |
| Region 1 = North Coast Region                                    |                                                                                                  |                                                                                                  |
| Region 2 = San Francisco Region                                  |                                                                                                  |                                                                                                  |
| Region 3 = Central Coast Region                                  |                                                                                                  |                                                                                                  |
| Region 4 = Los Angeles Region                                    |                                                                                                  |                                                                                                  |
| Region 5 = Central Valley Region                                 | 5                                                                                                |                                                                                                  |
| Region 6 = Lahontan Region                                       |                                                                                                  |                                                                                                  |
| Region 7 = Colorado River Region                                 |                                                                                                  |                                                                                                  |
| Region 8 = Santa Ana Region                                      |                                                                                                  |                                                                                                  |
| Region 9 = San Diego Region                                      |                                                                                                  |                                                                                                  |

: Summary of Water Boards Openscapes Cohorts by Region, Division, or Office (RDO)
