---
title: "2023 Water Boards Cohort"
---

*Cohort Instructors:* Corey Clatterbuck (OIMA), Anna Holder (OIMA)

*Cohort Mentors:* Devan Burke (OIMA), Tina Ures (DWQ)

-   Cohort Webpage (*coming soon!*)

In mid-August-mid-October 2023, the Water Boards cohort instructors and mentors will lead second Openscapes Champions Cohort at the Water Boards!

The 2023 Cohort will include [3 to 6 teams of no more than 6 individuals per team]{.underline}. **Water Boards teams will be able to apply for this opportunity starting in June 2023.**

## What makes a "good" team?

Characteristics of teams that will get the most return on their investment into the Champions Program include:

-   Team members are given the approval and support they need from their management to dedicate the [**time required to actively participate and engage in the Openscapes Process**]{.underline}. The minimum and required time commitment is 2-4 hours/week over 10 weeks for meetings and associated work
-   Teams that have at least one or two members who do some form of data management, analysis, visualization, or communication in their work on a regular basis. The more regular this work occurs (e.g. weekly is better than quarterly), and the more technically advanced they are (e.g. coding in R, Python or SQL is better than Excel), the more the entire team will get out of the process.
-   [**All**]{.underline} team members are interested in exploring the interconnected nature of open science and in taking time to reimagine data workflows and stewardship as a collaborative effort, develop modern skills that are of immediate value to them, and cultivate collaborative, inclusive, equitable, and kind teams and communities.
-   Teams want to evolve and invest in their culture, processes, and workflows so that they can embody the [better science for future us mindset](https://www.openscapes.org/blog/2021/09/15/better-science-for-future-us/).
    -   "Better science" means science that is more open, reproducible, efficient, and also more diverse, equitable, inclusive, kind.
    -   "Future us" is ourselves, teams, communities in the next hour, week, decades -- with a focus on onboarding ourselves and others to ongoing work.
