---
title: "Impacts"
---

Openscapes is an ongoing internal effort at the Water Boards, with immediate and long-term impacts across the organization. Below is a space of shared successes we've heard about or seen from teams who have joined a Champions Cohort at the Water Boards! If you would like to contribute to this list, please [submit an issue](https://github.com/CAWaterBoardDataCenter/swrcb-openscapes) to this Github repository!

## Individual team successes

-   In the Cohort, every team builds their [**Pathway**](https://openscapes.github.io/series/core-lessons/pathways.html) -- where are they in their work and where do they want to go? The Pathway is a living document and a place to share progress & successes!

> *(The Pathway) helped us be more conscious of what can be improved and also how we can improve. We were already aware of the 'problems' before but now there is a plan for next steps that we can all agree upon.*

-   **The PFAS Free Forum** -- A bimonthly meeting among State & Regional board staff to share, coordinate, and learn about PFAS data & methods. As PFAS research and policy is rapidly changing, the team is also building a Sharepoint site to share PFAS resources and communicate asynchronously between forums.

-   **SWAMP Manual** -- a manual written by current SWAMP members for on & offboarding SWAMP team members at State Board.

-   Mentor-led meetings/facilitation/skill building/leadership

-   Ongoing optional co-working among SWAMP team members as an agenda-free space to work on common tasks, knowledge sharing/skill building, and opportunity to pause and reflect on Water Boards work.

## Qualitative outcomes

> *Openscapes has encouraged me to manage my workflow better with "future me/us" in mind.*

-   Improved individual and team interactions

-   Foster a culture of inclusion and belonging where discussion of values is safe and welcomed

    -   Direct connection to Goal 2B of the Water Boards [Racial Equity Action Plan](https://www.waterboards.ca.gov/racial_equity/docs/racial-equity-action-plan-final-en.pdf)
