---
title: "About Openscapes at the Water Boards"
---

The Water Board's partnership with Openscapes began in 2021, when staff were onboarded as as mentors for multiple NOAA Champions Cohorts held in Fall 2021. Starting in 2022, the Water Boards, in partnership with [Openscapes](https://www.openscapes.org/), have been leading their own annual Champions Cohorts and intend to continue to scale the [Champions Program](https://www.openscapes.org/champions/) throughout the organization.

You can learn more about these experiences and processes in these Water Board authored blog posts:

-   [California Water Board Mentor Perspectives](https://www.openscapes.org/blog/2021/12/07/california-waterboards-mentors/) (Dec 2021)
-   [ESIP Better Science for Future Us - Planning for the Year of Open Science](https://www.openscapes.org/blog/2022/02/17/esip-winter-2022/) (Feb 2022)
-   [Adapting the Champions Program for the California Water Boards](https://www.openscapes.org/blog/2022/12/02/swrcb-2022/) (Dec 2022)

## Context

Over the last decade, there have been rapid changes within the scientific community to improve the quality of science -- these advances are not related to specific methodologies, but largely around scientific culture and collaboration (collectively, 'Open Science'). Many of the techniques -- including version control, code review, reproducible reports, project management, and leadership skills -- have been widely used by industry and academic partners, but have not seen wide use in government. Open Science fosters a more efficient and equitable working environment, via improved team collaboration and knowledge sharing.

In recent years, the State Water Board has committed to a number of cultural and programmatic changes related to [open data](https://www.waterboards.ca.gov/board_decisions/adopted_orders/resolutions/2018/rs2018_0032.pdf) and [racial equity](https://www.waterboards.ca.gov/racial_equity/). To date, the implementation and integration of open data principles throughout the Water Boards has come from a largely technical perspective with a focus on making process, data, code, publications, etc. more transparent, open, and accessible on websites like the [California Open Data Portal](https://data.ca.gov/), [databases](https://www.waterboards.ca.gov/resources/data_databases/), or [GitHub repositories](https://github.com/CAWaterBoardDataCenter). Implementation and operationalization of equity throughout the Water Boards has only just begun and, thus far, has focused on education and normalization of concepts related to equity. To successfully achieve the open data and equity outcomes we seek, it is crucial that we shift our perspectives, culture, and actions towards open science so that the principles of open data and equity are fully integrated.

## Why Openscapes?

The [Water Boards](https://www.waterboards.ca.gov/about_us/) have regulatory responsibility for protecting the water quality of nearly 1.6 million acres of lakes, 1.3 million acres of bays and estuaries, 211,000 miles of rivers and streams, and about 1,100 miles of exquisite California coastline.

The Water Board is committed to leading the state in promotion of openness and interoperability of water data. Ensuring information is accessible, discoverable, and usable by the public will foster entrepreneurship, innovation, and scientific discovery. The Water Board is also committed to advancing racial equity and is actively working toward a future where race no longer predicts a person's access to water or the quality of water resources they receive, where race does not predict professional outcomes for our employees, and where we consistently consider racial equity impacts before we make decisions.

[Openscapes'](https://www.openscapes.org/) long-term goal is to enable robust, inclusive, and enduring science- and data-driven solutions to global and time-sensitive challenges. They approach open science as a spectrum, as a behavior change, and as a movement. Data analysis and stewardship are entryways to meet scientists where they are, helping them develop new skill sets and mindsets while empowering them as leaders. The Openscapes Framework is team-based and particularly suited to the type of team projects that we work on.

Openscapes, through their [Champions Program](https://www.openscapes.org/champions/), provides a framework for education, integration, and operationalization of open science, equity, communication, and kindness into individual and team collaborations and workflows. Teams that participate in the Champions Program are empowered to evolve and invest in their culture, processes, and workflows so that they can embody the [better science for future us mindset](https://openscapes.github.io/series/mindset.html). The scaling of the Openscapes Champions Program throughout the Water Boards is helping our teams change their scientific and programmatic workflows to work more openly, reproducibly, efficiently and robustly, to advance the Water Boards' mission.

## Where we are now

Many state and federal agencies, including the Water Boards, are experiencing a number of pressures affecting agency science. Examples include:

-   New risks affecting the kind of science we do (climate change impacts - like drought, floods, and fires - on freshwater and marine ecosystems and public health) and requiring new analyses to deal with changing environments
-   Flat budgets amid rising operation costs and increasing costs of living (employees that leave may not be replaced)
-   A distributed workforce (employees based remotely or across multiple offices)
-   An aging workforce, associated risk of loss of data and institutional knowledge, and need for succession planning
-   Need for transparency to enhance public trust in agency science and decisions

Many Water Boards Divisions, Regions, Offices, and Programs are doing their best to implement these actions into their work. However, implementation to date has been somewhat separate, meaning some people work on implementing principles of open data while others work on implementing principles of equity. While limited staff bandwidth and resources are undoubtedly key contributors to this trend, it is also largely due to a lack of training, education, and guidance on how these principles and plans are integrated and inextricably linked to one another.

There is an urgent need to upskill the existing Water Boards workforce with modern tooling and collaborative approaches to help our agency be nimble and tackle the challenges of the 21st century. Doing so will increase efficiency, effectiveness, and build enduring resilience across Water Boards Divisions, Regions, Offices, and Programs.

Change requires both structure and flexibility, focused on inclusion and empathy, so we can elevate our peers from where they are. Similarly, collaborative team-based research requires non-technical changes to the way we work; these include documenting standard operating procedures, working inclusively within/across science centers and regional offices, and cultivating rather than reinventing products. Supporting this change in work culture demands a dynamic approach that leverages and amplifies ongoing work in global Open Science - and that is what Openscapes does, based on their team's transition to better science in less time.

## What we've done

In 2021, two staff from the Water Board's Office of Information Management and Analysis ([OIMA](https://www.waterboards.ca.gov/resources/oima/)) were assigned to serve as mentors for two Openscapes Cohorts: Fisheries Dependent Data Users ([FDD](https://openscapes.github.io/2021-fdd)) and NOAA's National Marine Fishery Service ([NMFS](https://openscapes.github.io/2021-noaa-nmfs/)) Champions Cohorts. During this time, OIMA staff were tasked with learning more about the Openscapes Champions Program and determining whether and how we could bring the Openscapes mindset and process to the Water Boards and our diverse network of partners and collaborators.

In 2022, we wanted to share what we learned and the Openscapes Champions Program as a whole with the Water Boards and our partners. We wanted to explore whether the Champions Program could realistically be scaled throughout the Water Boards given the workforce's limited bandwidth (available time and resources). So, we worked with the [Openscapes team](https://www.openscapes.org/team/) to plan and execute a Champions Cohort at the Water Boards. While cohorts are typically led by the Openscapes team, this was the first to be led by Openscapes mentors and the first Champions Cohort at a US state government agency. To learn more about other previous cohorts, explore the [Openscapes Champions Cohorts List](https://openscapes.github.io/events/#category=Champions%20Cohort).

The 2022 Water Boards Champions cohort ([2022-swrcb](https://github.com/Openscapes/2022-swrcb)) was developed to intentionally customize the Champions Program to better serve our current organizational framework and needs. This included working with managers from OIMA and the Division of Water Quality (DWQ) to select teams for the pilot, and customizing meeting length, structure, and content to center culture, equity, and the importance and benefits of documentation, and to give teams more time to dive into and discuss these topics.

## Where we're going

We have developed an [Openscapes Implementation Strategy for the Water Board](https://github.com/CAWaterBoardDataCenter/swrcb-openscapes/blob/main/SWRCB%20Openscapes%20Implementation%20Strategy_202302.pdf), and are getting ready to launch a larger cohort in 2023!

We are excited to work towards a future where the Water Boards workforce understands the interconnected nature of open data and equity principles and is able to clearly articulate the specific actions they (as individuals and/or teams) will take to evolve their processes, behaviors, and actions to be more open, inclusive, reproducible, and kind - and we know scaling the Openscapes Champions Program through the Water Boards will expedite our ability to get there.
